# Generated by Django 4.2 on 2023-04-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('orders', '0002_cart_cartentry_remove_order_coupon_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartentry',
            unique_together={('cart', 'product')},
        ),
    ]
