# Generated by Django 4.2 on 2023-04-21 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_shippingscope_deliveryservice_logo_and_more'),
        ('store', '0002_product_discount'),
        ('orders', '0005_order_alter_cartentry_options_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('delivery_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='services.deliveryservice', verbose_name='Delivery service')),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24, verbose_name='Price after discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_before_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24, verbose_name='Price before discount'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='The owner of the cart'),
        ),
        migrations.DeleteModel(
            name='CartEntry',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='the_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='the_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='store.product', verbose_name='Product name'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('the_cart', 'the_product')},
        ),
    ]
