# Generated by Django 4.2 on 2023-04-19 12:50

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_shippingscope_deliveryservice_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Brand name')),
                ('logo', models.ImageField(upload_to='images/store/brand_logos/', verbose_name='Brand logo')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=124, verbose_name='Category title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=124, populate_from='title', verbose_name='Category slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DealAndOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('initial_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=24, verbose_name='Initial quantity')),
                ('sold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=24, verbose_name='Sold quantity')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='Price per unit')),
                ('condition', models.CharField(choices=[('ref', 'Refurbished'), ('bra', 'Brand new'), ('old', 'Old items')], default='bra', max_length=3, verbose_name='Condition')),
                ('description', models.TextField(verbose_name='Product description')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=124, verbose_name='Subcategory title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=124, populate_from='title', unique=True, verbose_name='Subcategory slug')),
                ('photo', models.ImageField(upload_to='images/store/subcategory_photos/', verbose_name='Subcategory photo')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='store.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Product photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.product', verbose_name='Related parent product')),
            ],
            options={
                'verbose_name': 'Product photo',
                'verbose_name_plural': 'Product photos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.subcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='services.supplier', verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity_from', models.DecimalField(decimal_places=2, default=0, max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Beginning from')),
                ('quantity_to', models.DecimalField(decimal_places=2, default=0, max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='To and including')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price per unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='store.product', verbose_name='Related parent product')),
            ],
            options={
                'verbose_name': 'Price range',
                'verbose_name_plural': 'Price ranges',
                'ordering': ['quantity_from'],
            },
        ),
    ]
