# Generated by Django 4.2 on 2023-04-18 13:23

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24, verbose_name='Initial quantity'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24, verbose_name='Price per unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='sold_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24, verbose_name='Sold quantity'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=124, populate_from='title', unique=True, verbose_name='Subcategory slug'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
