# Generated by Django 4.2 on 2023-04-21 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_rating'),
        ('store', '0002_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='bought_products', through='users.Rating', to=settings.AUTH_USER_MODEL, verbose_name='Buyers'),
        ),
    ]
