# Generated by Django 4.2 on 2023-04-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Service name')),
            ],
            options={
                'verbose_name': 'Delivery service',
                'verbose_name_plural': 'Delivery services',
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Service name')),
                ('service_photo', models.ImageField(upload_to='images/services/service_photos/', verbose_name='Service photo')),
                ('service_icon', models.ImageField(upload_to='images/services/service_icons/', verbose_name='Service icon')),
            ],
            options={
                'verbose_name': 'Extra service',
                'verbose_name_plural': 'Extra services',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Supplier name')),
                ('logo', models.ImageField(upload_to='images/services/logos/', verbose_name='Supplier logo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified?')),
                ('shipping_scope', models.CharField(max_length=255, verbose_name='Shipping scope')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
